lb:
    command: load-balance
    image: corbinu/consul-nginx
    mem_limit: 1024m
    environment:
        CONSUL_IP:
        CONSUL_PORT:
        SERVICE: node-demo
    ports:
    - 80
    restart: always